file_format: "1"
id: niklasae-1
name: Chocofi niklasae-1
type: shield
url: https://github.com/leikoilja/zmk-config-temper/
requires: [pro_micro]
# exposes: [i2c_oled]
features:
  - keys
  - studio
  # - display
siblings:
  - niklasae_left
  - niklasae_right